package fr.eni.javaee.auctions.bll;

public interface CodesErreurBLL {
	int CHAMPS_PSEUDO_NON_SAISI_OU_TROP_LONG_ERREUR = 20_000;
	int CHAMPS_NOM_NON_SAISI_OU_TROP_LONG_ERREUR = 20_001;
	int CHAMPS_PRENOM_NON_SAISI_OU_TROP_LONG_ERREUR = 20_002;
	int CHAMPS_EMAIL_NON_SAISI_OU_TROP_LONG_ERREUR = 20_003;
	int CHAMPS_RUE_NON_SAISI_OU_TROP_LONG_ERREUR = 20_004;
	int CHAMPS_CODEPOSTAL_NON_SAISI_OU_TROP_LONG_ERREUR= 20_005;
	int CHAMPS_VILLE_NON_SAISI_OU_TROP_LONG_ERREUR= 20_006;
	int CHAMPS_MOTDEPASSE_NON_SAISI_OU_TROP_LONG_ERREUR= 20_007;
	int MOT_DE_PASSE_DIFFERENT= 20_008;
}
